// import {
//   MapContainer,
//   TileLayer,
//   Marker,
//   useMap,
//   Polyline,
// } from "react-leaflet";
// import { useEffect, useState } from "react";
// import "leaflet/dist/leaflet.css";
// import { bikeIcon, resturantIcon, homeIcon } from "./MapIcon";


// // Move map smoothly
// function RecenterMap({ position }) {
//   const map = useMap();

//   useEffect(() => {
//     if (!position || position[0] == null || position[1] == null) return;

//     map.flyTo(position, map.getZoom(), {
//       duration: 0.5,
//     });
//   }, [position, map]);

//   return null;
// }

// function LiveMap({ position, route, startPoint, endPoint ,trail}) {
//   return (
//     <div style={{ padding: "20px" }}>
//       <MapContainer
//         center={
//           position && position[0] != null && position[1] != null
//             ? position
//             : [27.7172, 85.324]
//         }
//         zoom={15}
//         style={{ height: "500px", width: "100%", borderRadius: "12px" }}
//       >
//         <TileLayer url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png" />

//         <RecenterMap position={position} />

//         {/* Rider */}
//         {/* <Marker position={position} icon={bikeIcon} /> */}
//         {position && position[0] != null && position[1] != null && (
//           <Marker position={position} icon={bikeIcon} />
//         )}

//         {/* Start & End */}
//         <Marker position={startPoint} icon={resturantIcon} />
//         <Marker position={endPoint} icon={homeIcon} />

//         {/* Route line */}
//         {/* <Polyline positions={route.map((p) => [p.lat, p.lng])} color="blue" /> */}
//         <Polyline
//           positions={(route || [])
//             .filter(
//               (p) =>
//                 p && typeof p.lat === "number" && typeof p.lng === "number",
//             )
//             .map((p) => [p.lat, p.lng])}
//           color="blue"
//         />
//         {/* Rider trail */}
//         <Polyline
//           positions={(trail || []).map((p) => [p.lat, p.lng])}
//           color="red"
//         />
//       </MapContainer>
//     </div>
//   );
// }

// export default LiveMap;












// Yes, both polylines are important because one represents the planned route (blue)
//  generated by the routing service, while the other represents the real-time movement 
//  of the rider (red) coming from backend GPS updates. Together they allow comparison
//   between expected and actual delivery progress.


























import {
  MapContainer,
  TileLayer,
  Marker,
  useMap,
  Polyline,
} from "react-leaflet";
import { useEffect } from "react";
import "leaflet/dist/leaflet.css";
import { bikeIcon, resturantIcon, homeIcon } from "./MapIcon";

function RecenterMap({ position }) {
  const map = useMap();

  useEffect(() => {
    if (!position?.length) return;

    map.flyTo(position, map.getZoom(), {
      duration: 0.5,
    });
  }, [position, map]);

  return null;
}

function LiveMap({ position, route, startPoint, endPoint, trail }) {
  return (
    <div style={{ padding: "20px" }}>
      <MapContainer
        center={position?.length ? position : [27.7172, 85.324]}
        zoom={15}
        style={{ height: "500px", width: "100%", borderRadius: "12px" }}
      >
        <TileLayer url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png" />

        <RecenterMap position={position} />

        {/* Rider */}
        {position?.length === 2 && (
  <Marker 
    key={`rider-${position[0]}-${position[1]}`} // 👈 Add this unique key
    position={position} 
    icon={bikeIcon} 
  />
)}

        {/* Start */}
        {startPoint?.length && (
          <Marker position={startPoint} icon={resturantIcon} />
        )}

        {/* End */}
        {endPoint?.length && (
          <Marker position={endPoint} icon={homeIcon} />
        )}

        {/* Route */}
        <Polyline
          positions={(route || [])
            .filter(p => p?.lat && p?.lng)
            .map(p => [p.lat, p.lng])}
          color="blue"
        />

        {/* Trail */}
        <Polyline
          positions={(trail || [])
            .slice(-100)
            .map(p => [p.lat, p.lng])}
          color="red"
        />
      </MapContainer>
    </div>
  );
}

export default LiveMap;